# Site settings
title: MiKorotkov
baseurl: ""
url: "https://kssim.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"
google_tag_manager: 'GTM-TG8FGPC'

# Author
author:
  name: Michael Korotkov
  desc: Analytics and data warehousing professional
  email: korotkov.michael@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: false
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: mikorotkov
  mastodon: mikorotkov
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/michaelkorotkov/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  stack_overflow: https://stackoverflow.com/users/15260395/michael-korotkov
  steam:
  tumblr:
  gitlab:
#  twitter: mikorotkov
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:categories/:slug
#/:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 10
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
